// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdbqyaznwpkpxxmhkdtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkYnF5YXpud3BrcHh4bWhrZHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjgxODEsImV4cCI6MjA2MDQwNDE4MX0.nDkug3wXhdUGo6UrTMRTho8N3GogsNzzK7dnlLJl8_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});